# Generated by Django 5.2.6 on 2026-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='circuit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
