import os
import tempfile
import subprocess
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, viewsets, serializers
from .models import Circuit

class CircuitSerializer(serializers.ModelSerializer):
    class Meta:
        model = Circuit
        fields = '__all__'

class CircuitViewSet(viewsets.ModelViewSet):
    queryset = Circuit.objects.all()
    serializer_class = CircuitSerializer

class CompileArduinoView(APIView):
    """
    Receives frontend C++ code, compiles it via arduino-cli into an AVR ELF/HEX, 
    and pipes the generated bin string directly back down to avr8js.
    """
    def post(self, request):
        code = request.data.get('code', '')
        if not code:
            return Response({'error': 'No custom C++ code provided in payload.'}, status=status.HTTP_400_BAD_REQUEST)

        # Build an isolated ephemeral workspace so concurrent UI compilation requests don't collide
        with tempfile.TemporaryDirectory() as tmpdir:
            sketch_dir = os.path.join(tmpdir, 'sketch')
            os.makedirs(sketch_dir)
            sketch_file = os.path.join(sketch_dir, 'sketch.ino')
            
            with open(sketch_file, 'w') as f:
                f.write(code)

            build_dir = os.path.join(tmpdir, 'build')
            os.makedirs(build_dir)

            # Trigger localized arduino-cli toolchain
            # Requires `arduino-cli core install arduino:avr` globally hosted on the host container natively
            cmd = [
                'arduino-cli', 'compile', 
                '-b', 'arduino:avr:uno', 
                '--build-path', build_dir, 
                sketch_dir
            ]
            
            result = subprocess.run(cmd, capture_output=True, text=True)
            
            if result.returncode != 0:
                print("AVR GCC LINKER ERROR:")
                print(result.stdout)
                print(result.stderr)
                return Response(
                    {'error': result.stderr or result.stdout}, 
                    status=status.HTTP_400_BAD_REQUEST
                )

            # Extract the generated Intel HEX flash array generated by the GCC toolchain
            hex_file = os.path.join(build_dir, 'sketch.ino.hex')
            if not os.path.exists(hex_file):
                return Response({'error': 'Compilation reported success but Arduino Linker failed to push physical .hex file.'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

            with open(hex_file, 'r') as f:
                hex_content = f.read()

            return Response({'hex': hex_content}, status=status.HTTP_200_OK)
